---
title: "Chutes and Ladders"
author: "Romy Gou"
output: pdf_document
---

```{r, error = TRUE}
source("Chutes_and_Ladders.R")
```

```{r, error = TRUE}
board <- list(dim = c(10, 10),
              chutes = c(16, 6, 47, 26, 49, 11, 56, 53, 62, 19, 64, 60, 87, 24, 93, 73, 95, 75, 98, 78),
              ladders = c(1, 38, 4, 14, 9, 31, 21, 42, 28, 84, 36, 44, 51, 67, 71, 91, 80, 100))
```

```{r, error = TRUE}
par(mar = c(0, 0, 0, 0)) 
show_board(board)
```

```{r, error = TRUE}
miniboard1 <- list(dim = c(7, 6),
                   chutes = c(16, 6, 30, 18, 35, 24, 40, 26),
                   ladders = c(1, 23, 9, 27, 20, 31, 33, 41))
par(mar = c(0, 0, 0, 0))
show_board(miniboard1)
```

```{r, error = TRUE}
miniboard2 <- list(dim = c(9, 7),
                   chutes = c(16, 3, 31, 15, 35, 21, 62, 48),
                   ladders = c(9, 22, 13, 30, 24, 37, 29, 41, 33, 39, 43, 54))
par(mar = c(0, 0, 0, 0))
show_board(miniboard2)
```

```{r, error = TRUE}
miniboard3 <- list(dim = c(9, 8),
                   chutes = c(),
                   ladders = c())
par(mar = c(0, 0, 0, 0))
show_board(miniboard3)
```

```{r, error = TRUE}
set.seed(5)
play_solo(board, verbose = TRUE)
```

# Monte Carlo Simulation Study

```{r, error = TRUE, echo = TRUE, results='hide'}
# run 10,000 games
set.seed(5)
MC_sim <- replicate(10000, play_solo(board, verbose = FALSE))
```

```{r}
total_turns <- unlist(MC_sim[1, ])
turn_hist <- hist(total_turns,
                  main = "Histogram of turns to complete a game of chutes and ladders",
                  xlab = "Number of turns per game",
                  breaks = 50)
```

```{r}
summary(total_turns)[1]
freq_table <- table(total_turns)
freq_table[1] #frequency for 7 turns
```

```{r}
summary(total_turns)[6]
```

```{r}
summary(total_turns)[3]
```

```{r}
summary(total_turns)[4]
```

```{r}
prop_table <- freq_table / sum(freq_table)
sum(prop_table[-1:-93])
```

```{r}
sum(prop_table[1:4])
```

```{r}
total_ladder <- 0
for (i in 1:10000) {
  total_ladder <- total_ladder + MC_sim[3, ][[i]]
  names(total_ladder) <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
}

total_ladder[9] / (sum(total_ladder) - total_ladder[9])
```

```{r}
total_chute <- 0
for (i in 1:10000) {
  total_chute <- total_chute + MC_sim[2, ][[i]]
  names(total_chute) <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
}

chute_plot <- barplot(total_chute,
                      main = "Number of times each chute was used during 10000 games of chutes and ladders",
                      xlab = "Chute number",
                      ylab = "Frequency")
```

```{r}
ladder_plot <- barplot(total_ladder,
                      main = "Number of times each ladder was used during 10000 games of chutes and ladders",
                      xlab = "Ladder number",
                      ylab = "Frequency")
```

